/**
 * 2dfea save/load JSON — v1.0.0 Zod schema.
 *
 * This file is the single source of truth for the file format. From this
 * schema we derive:
 *   - the runtime validator used by the import path (`ModelFileV1Schema.safeParse`)
 *   - the TypeScript type `ModelFileV1` consumed by canonicalize / applyToStore
 *   - the published JSON Schema document at public/schemas/2dfea-model-v1.json
 *     (regenerated by src/io/generateJsonSchema.ts on every prebuild)
 *
 * Design rules (see docs/plans/save-load-json.md §5.2):
 *   1. Numeric fields with physical units carry the unit in their name
 *      (`x_m`, `fy_kN`, `E_GPa`, etc.).
 *   2. Top-level envelope (`schemaVersion`, `metadata`, `model`, `_comments`)
 *      is strict — unknown sibling keys are rejected.
 *   3. Inner extensible layers — `metadata`, `model`, `model.loads`,
 *      `model.idCounters`, every entity object — use `.passthrough()` so a
 *      future MINOR bump (e.g. `Element.sectionRef`, `loads.thermal`,
 *      `idCounters.nextSectionRefNumber`) parses cleanly in older readers.
 *   4. `metadata.units` is `z.literal()`-pinned. v1 is not unit-configurable.
 *   5. Every numeric is `.finite()` (rejects NaN / Infinity).
 *   6. Direction enums match types.ts case-sensitively (Fx/Fy local,
 *      FX/FY global) — this is a known AI-generation footgun.
 *   7. `loads.{thermal,prescribedDisplacement,...}` future load types
 *      pass through via `.catchall(z.array(z.unknown()))`.
 *
 * Forward-compat hardening landed in commit b7731ac on master before this
 * PR — that commit's amendments to the plan are encoded here. Only the
 * envelope is strict; everything else is permissive.
 */
import { z } from 'zod';
import { CURRENT_SCHEMA_VERSION, V1_UNITS } from './schemaVersion';

// Re-export V1_UNITS so existing consumers of `./schema` keep working.
export { V1_UNITS } from './schemaVersion';

// ----------------------------------------------------------------------------
// Enums (kept in sync with src/analysis/types.ts)
// ----------------------------------------------------------------------------

const SupportTypeSchema = z.enum(['fixed', 'pinned', 'roller-x', 'roller-y', 'free']);

/** Distributed-load direction. Lowercase = local, uppercase = global. */
const DistributedDirectionSchema = z.enum(['Fx', 'Fy', 'FX', 'FY']);

/** Element-point-load direction. Lowercase = local, uppercase = global. */
const ElementPointDirectionSchema = z.enum(['Fx', 'Fy', 'Mz', 'FX', 'FY', 'MZ']);

// ----------------------------------------------------------------------------
// Entity schemas — each uses .passthrough() for forward-compat (sectionRef,
// materialRef, releases, etc. are MINOR additions in future versions).
// ----------------------------------------------------------------------------

const NodeSchema = z
  .object({
    name: z.string(),
    x_m: z.number().finite(),
    y_m: z.number().finite(),
    support: SupportTypeSchema,
  })
  .passthrough();

const ElementSchema = z
  .object({
    name: z.string(),
    nodeI: z.string(),
    nodeJ: z.string(),
    E_GPa: z.number().finite(),
    I_m4: z.number().finite(),
    A_m2: z.number().finite(),
    // v1.1.0 (additive, optional): per-end Mz release flags. Default-absent
    // = rigid. See docs/plans/member-end-releases-mz.md §5.2 for the locked
    // flat-sibling shape and §5.9 for the schema-bump rationale.
    releaseStartMz: z.boolean().optional(),
    releaseEndMz: z.boolean().optional(),
  })
  .passthrough();

const NodalLoadSchema = z
  .object({
    id: z.string(),
    node: z.string(),
    fx_kN: z.number().finite(),
    fy_kN: z.number().finite(),
    mz_kNm: z.number().finite(),
    case: z.string().optional(),
  })
  .passthrough();

const DistributedLoadSchema = z
  .object({
    id: z.string(),
    element: z.string(),
    direction: DistributedDirectionSchema,
    w1_kN_per_m: z.number().finite(),
    w2_kN_per_m: z.number().finite(),
    x1_m: z.number().finite(),
    x2_m: z.number().finite(),
    case: z.string().optional(),
  })
  .passthrough();

const ElementPointLoadSchema = z
  .object({
    id: z.string(),
    element: z.string(),
    distance_m: z.number().finite(),
    direction: ElementPointDirectionSchema,
    magnitude_kN_or_kNm: z.number().finite(),
    case: z.string().optional(),
  })
  .passthrough();

const LoadCaseSchema = z
  .object({
    name: z.string(),
    description: z.string().optional(),
  })
  .passthrough();

const LoadCombinationSchema = z
  .object({
    name: z.string(),
    description: z.string().optional(),
    factors: z.record(z.string(), z.number().finite()),
  })
  .passthrough();

// ----------------------------------------------------------------------------
// Loads block — known keys plus catchall for future load types
// ----------------------------------------------------------------------------

const LoadsSchema = z
  .object({
    nodal: z.array(NodalLoadSchema),
    distributed: z.array(DistributedLoadSchema),
    elementPoint: z.array(ElementPointLoadSchema),
  })
  .catchall(z.array(z.unknown()));

// ----------------------------------------------------------------------------
// idCounters — known counters plus passthrough for future ones (sectionRef etc.)
// ----------------------------------------------------------------------------

const IdCountersSchema = z
  .object({
    nextNodeNumber: z.number().int().nonnegative().finite(),
    nextElementNumber: z.number().int().nonnegative().finite(),
    nextNodalLoadNumber: z.number().int().nonnegative().finite(),
    nextPointLoadNumber: z.number().int().nonnegative().finite(),
    nextDistributedLoadNumber: z.number().int().nonnegative().finite(),
    nextLineLoadNumber: z.number().int().nonnegative().finite(),
  })
  .passthrough();

// ----------------------------------------------------------------------------
// activeResultView — small tagged union
// ----------------------------------------------------------------------------

const ActiveResultViewSchema = z
  .object({
    type: z.enum(['case', 'combination']),
    name: z.string().nullable(),
  })
  .passthrough();

// ----------------------------------------------------------------------------
// model — TRACKED_KEYS plus activeLoadCase / activeResultView / idCounters.
// Passthrough so MINOR-bump siblings (e.g. `materials`, `sections`) round-trip.
// ----------------------------------------------------------------------------

const ModelSchema = z
  .object({
    nodes: z.array(NodeSchema),
    elements: z.array(ElementSchema),
    loads: LoadsSchema,
    loadCases: z.array(LoadCaseSchema),
    loadCombinations: z.array(LoadCombinationSchema),
    activeLoadCase: z.string().nullable(),
    activeResultView: ActiveResultViewSchema,
    idCounters: IdCountersSchema,
  })
  .passthrough();

// ----------------------------------------------------------------------------
// metadata — pin the units block, passthrough everything else
// ----------------------------------------------------------------------------

const UnitsSchema = z.object({
  length: z.literal(V1_UNITS.length),
  force: z.literal(V1_UNITS.force),
  moment: z.literal(V1_UNITS.moment),
  stress: z.literal(V1_UNITS.stress),
  areaMomentOfInertia: z.literal(V1_UNITS.areaMomentOfInertia),
  area: z.literal(V1_UNITS.area),
});

const MetadataSchema = z
  .object({
    appVersion: z.string(),
    exportedAt: z.string(),
    name: z.string().optional(),
    description: z.string().optional(),
    author: z.string().nullable().optional(),
    units: UnitsSchema,
  })
  .passthrough();

// ----------------------------------------------------------------------------
// _comments — parallel annotation map. Optional; entirely free-form strings.
// ----------------------------------------------------------------------------

const CommentsSchema = z
  .object({
    nodes: z.record(z.string(), z.string()).optional(),
    elements: z.record(z.string(), z.string()).optional(),
    loads: z.record(z.string(), z.string()).optional(),
    loadCases: z.record(z.string(), z.string()).optional(),
    loadCombinations: z.record(z.string(), z.string()).optional(),
  })
  .passthrough();

// ----------------------------------------------------------------------------
// Top-level envelope — STRICT. Unknown sibling keys to schemaVersion / metadata
// / model / _comments are rejected.
// ----------------------------------------------------------------------------

export const ModelFileV1Schema = z
  .object({
    schemaVersion: z.literal(CURRENT_SCHEMA_VERSION),
    metadata: MetadataSchema,
    model: ModelSchema,
    _comments: CommentsSchema.optional(),
  })
  .strict();

export type ModelFileV1 = z.infer<typeof ModelFileV1Schema>;

// ----------------------------------------------------------------------------
// Forward-compat warn-on-unknown-keys helper.
//
// Walks the parsed file looking for keys not in the v1 known-keys set at
// each layer that uses .passthrough(). Emits a single deduplicated
// console.warn enumerating each unknown key it encountered, prefixed by
// path. Old code reading a newer MINOR file does NOT reject — it tells
// the developer what it ignored.
// ----------------------------------------------------------------------------

const KNOWN_METADATA_KEYS = new Set([
  'appVersion',
  'exportedAt',
  'name',
  'description',
  'author',
  'units',
]);

const KNOWN_MODEL_KEYS = new Set([
  'nodes',
  'elements',
  'loads',
  'loadCases',
  'loadCombinations',
  'activeLoadCase',
  'activeResultView',
  'idCounters',
]);

const KNOWN_LOADS_KEYS = new Set(['nodal', 'distributed', 'elementPoint']);

const KNOWN_ID_COUNTER_KEYS = new Set([
  'nextNodeNumber',
  'nextElementNumber',
  'nextNodalLoadNumber',
  'nextPointLoadNumber',
  'nextDistributedLoadNumber',
  'nextLineLoadNumber',
]);

const KNOWN_NODE_KEYS = new Set(['name', 'x_m', 'y_m', 'support']);
const KNOWN_ELEMENT_KEYS = new Set([
  'name',
  'nodeI',
  'nodeJ',
  'E_GPa',
  'I_m4',
  'A_m2',
  // v1.1.0 additions — keep listed so the unknown-keys diagnostic doesn't
  // fire on legitimate v1.1.0 fields when a v1.1.0 reader loads a v1.1.0 file.
  'releaseStartMz',
  'releaseEndMz',
]);
const KNOWN_NODAL_LOAD_KEYS = new Set(['id', 'node', 'fx_kN', 'fy_kN', 'mz_kNm', 'case']);
const KNOWN_DISTRIBUTED_LOAD_KEYS = new Set([
  'id',
  'element',
  'direction',
  'w1_kN_per_m',
  'w2_kN_per_m',
  'x1_m',
  'x2_m',
  'case',
]);
const KNOWN_ELEMENT_POINT_LOAD_KEYS = new Set([
  'id',
  'element',
  'distance_m',
  'direction',
  'magnitude_kN_or_kNm',
  'case',
]);

function unknownKeysOf(obj: unknown, knownSet: Set<string>): string[] {
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return [];
  return Object.keys(obj as Record<string, unknown>).filter((k) => !knownSet.has(k));
}

/**
 * Walk a parsed v1 file and collect the set of unknown keys at each
 * passthrough layer. Returns a deduped, sorted array of `path` strings
 * suitable for `console.warn`.
 *
 * Public for testing (forwardCompat.test.ts).
 */
export function collectUnknownKeys(file: ModelFileV1): string[] {
  const found = new Set<string>();

  // metadata.*
  for (const k of unknownKeysOf(file.metadata, KNOWN_METADATA_KEYS)) {
    found.add(`metadata.${k}`);
  }

  // model.*
  for (const k of unknownKeysOf(file.model, KNOWN_MODEL_KEYS)) {
    found.add(`model.${k}`);
  }

  // model.loads.* (catchall; nodal/distributed/elementPoint are known)
  for (const k of unknownKeysOf(file.model.loads, KNOWN_LOADS_KEYS)) {
    found.add(`model.loads.${k}`);
  }

  // model.idCounters.*
  for (const k of unknownKeysOf(file.model.idCounters, KNOWN_ID_COUNTER_KEYS)) {
    found.add(`model.idCounters.${k}`);
  }

  // Per-entity unknown keys, deduped to a single shape report
  // (e.g. all Element.sectionRef occurrences fold to "model.elements[].sectionRef").
  const collectArrayUnknown = (arr: unknown[], known: Set<string>, prefix: string) => {
    for (const x of arr) {
      for (const k of unknownKeysOf(x, known)) {
        found.add(`${prefix}.${k}`);
      }
    }
  };

  collectArrayUnknown(file.model.nodes, KNOWN_NODE_KEYS, 'model.nodes[]');
  collectArrayUnknown(file.model.elements, KNOWN_ELEMENT_KEYS, 'model.elements[]');
  collectArrayUnknown(file.model.loads.nodal, KNOWN_NODAL_LOAD_KEYS, 'model.loads.nodal[]');
  collectArrayUnknown(
    file.model.loads.distributed,
    KNOWN_DISTRIBUTED_LOAD_KEYS,
    'model.loads.distributed[]'
  );
  collectArrayUnknown(
    file.model.loads.elementPoint,
    KNOWN_ELEMENT_POINT_LOAD_KEYS,
    'model.loads.elementPoint[]'
  );

  return Array.from(found).sort();
}

/**
 * Emit a single, deduplicated `console.warn` listing every unknown key
 * encountered. No-op when nothing unknown is found. Called from the
 * import path after Zod parse succeeds.
 */
export function warnUnknownKeys(file: ModelFileV1): void {
  const keys = collectUnknownKeys(file);
  if (keys.length === 0) return;
  console.warn(
    '[Import] Unknown keys (passed through, ignored by v' +
      CURRENT_SCHEMA_VERSION +
      ' reader):',
    keys
  );
}
