/** Norwegian (bokmål) and English strings for reports and explanations. */
export type Lang = 'nb' | 'en';

const nb = {
  report: 'Rapport',
  project: 'Prosjekt',
  generated: 'Generert',
  geometry: 'Geometri',
  materials: 'Materialer',
  boundaryConditions: 'Randbetingelser',
  timeSeries: 'Tidsserier',
  analysis: 'Analyse',
  mesh: 'Elementnett',
  results: 'Resultater',
  rebarTable: 'Armeringstabell',
  metrics: 'Nøkkeltall',
  warnings: 'Advarsler',
  checks: 'Kontroller',
  assumptions: 'Forutsetninger',
  inputs: 'Inndata',
  region: 'Område',
  material: 'Materiale',
  area: 'Areal',
  source: 'Kilde',
  quality: 'Kvalitet',
  name: 'Navn',
  type: 'Type',
  edges: 'Kanter',
  series: 'Serie',
  parameters: 'Parametre',
  mode: 'Modus',
  duration: 'Varighet',
  timeStep: 'Tidssteg',
  initialTemperature: 'Starttemperatur',
  outputInterval: 'Lagringsintervall',
  nodes: 'Noder',
  elements: 'Elementer',
  minAngle: 'Minste vinkel',
  probe: 'Målepunkt',
  temperature: 'Temperatur',
  time: 'Tid',
  none: 'ingen',
  steady: 'stasjonær',
  transient: 'transient',
  periodic: 'periodisk',
  bar: 'Stang',
  diameter: 'Ø',
  reducedStrength: 'k_s(θ)',
  figureField: 'Temperaturfelt',
  figureSeries: 'Temperatur mot tid',
  figureModel: 'Modell',
  figureProfile: 'Temperaturprofil',
  caption: 'Figur',
  energyBalance: 'Energibalanse',
  imbalance: 'ubalanse',
  solver: 'Løser',
  steps: 'tidssteg',
  newton: 'Newton-iterasjoner',
  wallTime: 'regnetid',
  fireCurve: 'brannkurve',
  ambient: 'omgivelse',
  page: 'Side',
  unitMm: 'mm',
  value: 'Verdi',
  unit: 'Enhet',
  explanationTitle: 'Forklaring',
};

const en: typeof nb = {
  report: 'Report',
  project: 'Project',
  generated: 'Generated',
  geometry: 'Geometry',
  materials: 'Materials',
  boundaryConditions: 'Boundary conditions',
  timeSeries: 'Time series',
  analysis: 'Analysis',
  mesh: 'Mesh',
  results: 'Results',
  rebarTable: 'Rebar table',
  metrics: 'Metrics',
  warnings: 'Warnings',
  checks: 'Checks',
  assumptions: 'Assumptions',
  inputs: 'Inputs',
  region: 'Region',
  material: 'Material',
  area: 'Area',
  source: 'Source',
  quality: 'Quality',
  name: 'Name',
  type: 'Type',
  edges: 'Edges',
  series: 'Series',
  parameters: 'Parameters',
  mode: 'Mode',
  duration: 'Duration',
  timeStep: 'Time step',
  initialTemperature: 'Initial temperature',
  outputInterval: 'Output interval',
  nodes: 'Nodes',
  elements: 'Elements',
  minAngle: 'Min angle',
  probe: 'Probe',
  temperature: 'Temperature',
  time: 'Time',
  none: 'none',
  steady: 'steady state',
  transient: 'transient',
  periodic: 'periodic',
  bar: 'Bar',
  diameter: 'Ø',
  reducedStrength: 'k_s(θ)',
  figureField: 'Temperature field',
  figureSeries: 'Temperature versus time',
  figureModel: 'Model',
  figureProfile: 'Temperature profile',
  caption: 'Figure',
  energyBalance: 'Energy balance',
  imbalance: 'imbalance',
  solver: 'Solver',
  steps: 'time steps',
  newton: 'Newton iterations',
  wallTime: 'wall time',
  fireCurve: 'fire curve',
  ambient: 'ambient',
  page: 'Page',
  unitMm: 'mm',
  value: 'Value',
  unit: 'Unit',
  explanationTitle: 'Explanation',
};

export type StringKey = keyof typeof nb;

export function strings(lang: Lang): Record<StringKey, string> {
  return lang === 'en' ? en : nb;
}

export function bcTypeName(t: string, lang: Lang): string {
  const map: Record<Lang, Record<string, string>> = {
    nb: { fixed: 'fast temperatur', convection: 'konveksjon', 'convection-radiation': 'konveksjon + stråling', flux: 'varmestrøm', insulated: 'isolert' },
    en: { fixed: 'fixed temperature', convection: 'convection', 'convection-radiation': 'convection + radiation', flux: 'heat flux', insulated: 'insulated' },
  };
  return map[lang][t] ?? t;
}
