/** Human/LLM-readable command catalogue for `describe_capabilities`. Keep in sync with commands/types.ts. */
export interface CommandDescription {
  type: string;
  description: string;
  fields: Record<string, string>;
}

const EDGE = 'EdgeRef { regionId, ring (0 = outer, k = hole k), edgeIndex (edge i runs from vertex i to i+1, counter-clockwise; on a rectangle from a bottom-left origin: 0 = bottom, 1 = right, 2 = top, 3 = left) }';
const SHAPE = 'PrimitiveShape: {kind:"rect",x,y,width,height} | {kind:"circle",cx,cy,r,segments?} | {kind:"ellipse",cx,cy,rx,ry} | {kind:"regularPolygon",cx,cy,r,n,rotationDeg?} | {kind:"polygon",points:[[x,y],...]} | {kind:"polygonWithHoles",polygon:{outer,holes}} — all mm';

export function describeCommands(): CommandDescription[] {
  return [
    { type: 'project.rename', description: 'Rename the project.', fields: { name: 'string' } },
    { type: 'project.setSettings', description: 'Patch project settings.', fields: { patch: 'Partial<{coverReference:"surface"|"centre", origin:"bbox-min"|"centroid"|[x,y], ambientTemperature:number °C, language:"nb"|"en", meshStirrups:boolean, csv:{separator,decimal}}>' } },
    { type: 'project.setMesh', description: 'Patch mesh settings.', fields: { patch: 'Partial<{preset:"coarse"|"normal"|"fine"|"custom", boundarySize, interiorSize, growth, rebarSize, rebarSegments, minAngle, maxElements}> (mm)' } },
    { type: 'region.addPrimitive', description: 'Add a region from a primitive shape.', fields: { shape: SHAPE, name: 'string?', materialId: 'string? (default: first concrete material in the project)', id: 'string?' } },
    { type: 'region.add', description: 'Add a region from an explicit polygon (mm, outer ring CCW, holes CW, rings not closed).', fields: { region: '{ id?, name, polygon:{outer:[[x,y]...], holes:[[[x,y]...]...]}, materialId, source:"drawn"|"imported" }' } },
    { type: 'region.update', description: 'Patch a region (name, polygon, materialId, visible, locked, color).', fields: { id: 'string', patch: 'Partial<Region>' } },
    { type: 'region.setVertex', description: 'Move one vertex.', fields: { id: 'string', ring: 'number', index: 'number', point: '[x,y] mm' } },
    { type: 'region.insertVertex', description: 'Insert a vertex on an edge (default at its midpoint).', fields: { id: 'string', ring: 'number', edgeIndex: 'number', point: '[x,y]?' } },
    { type: 'region.deleteVertex', description: 'Delete a vertex.', fields: { id: 'string', ring: 'number', index: 'number' } },
    { type: 'region.setMaterial', description: 'Assign a material to regions.', fields: { ids: 'string[]', materialId: 'string | null' } },
    { type: 'region.boolean', description: 'Union / subtract / intersect / xor the target with the tool regions; the result replaces the target, tools are deleted unless keepTools.', fields: { op: '"union"|"subtract"|"intersect"|"xor"', targetId: 'string', toolIds: 'string[]', keepTools: 'boolean?' } },
    { type: 'region.subtractShape', description: 'Cut a hole or a notch with a primitive shape (voids, cut-outs, hollow sections).', fields: { id: 'string', shape: SHAPE } },
    { type: 'region.addHole', description: 'Add a hole given as a ring fully inside the region.', fields: { id: 'string', ring: '[[x,y]...]' } },
    { type: 'region.offset', description: 'Offset the outline inward (negative) or outward (positive), e.g. a cover line.', fields: { id: 'string', distance: 'mm', asNew: 'boolean? (keep the original and add the offset as a new region)', name: 'string?' } },
    { type: 'region.split', description: 'Split a region by a line.', fields: { id: 'string', line: '[[x1,y1],[x2,y2]]' } },
    { type: 'region.fillet', description: 'Round a corner.', fields: { id: 'string', ring: 'number?', vertexIndex: 'number', radius: 'mm', segments: 'number?' } },
    { type: 'region.chamfer', description: 'Chamfer a corner (common fire-design detail).', fields: { id: 'string', ring: 'number?', vertexIndex: 'number', distance: 'mm' } },
    { type: 'region.mergeCollinear', description: 'Remove vertices on straight edges.', fields: { id: 'string', toleranceDeg: 'number?' } },
    { type: 'region.delete', description: 'Delete regions; attached rebars and boundary conditions are deleted or detached.', fields: { ids: 'string[]', dependents: '"delete"|"detach"' } },
    { type: 'entities.transform', description: 'Move, rotate, mirror or scale regions, rebars, probes, line probes.', fields: { ids: 'string[]', transform: '{kind:"move",dx,dy} | {kind:"rotate",cx,cy,angleDeg} | {kind:"mirror",axis:"x"|"y"|{p1,p2}} | {kind:"scale",cx,cy,sx,sy}' } },
    { type: 'entities.copy', description: 'Copy entities by an offset, `count` times (linear array).', fields: { ids: 'string[]', dx: 'mm', dy: 'mm', count: 'number?' } },
    { type: 'entities.polarArray', description: 'Polar array around a centre.', fields: { ids: 'string[]', cx: 'mm', cy: 'mm', count: 'number', angleDeg: 'total angle' } },
    { type: 'entities.delete', description: 'Delete any entities by id.', fields: { ids: 'string[]' } },
    { type: 'template.create', description: 'Create a parametric section. Templates: rect-beam (b,h), t-beam, inverted-t, l-section, i-section, box, circle-column (d), hollow-core-strip, layered-wall, wall-corner, floor-junction, ground-foundation. Regions keep their parameter panel.', fields: { templateId: 'string', params: 'Record<string, number|string|boolean> (mm)', materialId: 'string? | null', name: 'string?', id: 'string?' } },
    { type: 'template.update', description: 'Change template parameters of a templated region.', fields: { regionId: 'string', params: 'Record<string, number|string|boolean>' } },
    { type: 'material.add', description: 'Add a custom material.', fields: { material: 'Material without id (model: constant | table | concrete-en1992-1-2 | steel-en1993-1-2 | timber-en1995-1-2 | air-layer-iso6946)' } },
    { type: 'material.addFromLibrary', description: 'Add a library material to the project (resolved copy with citation). Idempotent by id.', fields: { libraryId: 'string (search_library)', id: 'string?', patch: 'Partial<Material>? (e.g. model parameters: moisture, conductivity bound)' } },
    { type: 'material.update', description: 'Patch a project material.', fields: { id: 'string', patch: 'Partial<Material>' } },
    { type: 'material.delete', description: 'Delete an unused material.', fields: { id: 'string' } },
    { type: 'rebarSet.add', description: 'Add a reinforcement set that follows the host geometry.', fields: { set: `{ id?, name, kind:"edge"|"corner"|"stirrup"|"grid"|"ring"|"manual", regionId, edgeRef?: ${EDGE}, corners?: number[], diameter mm, materialId, strengthClassId?, cover mm, count?, spacing?, spacingX?, spacingY?, startOffset?, endOffset?, meshed? }` } },
    { type: 'rebarSet.update', description: 'Patch a set; bars regenerate.', fields: { id: 'string', patch: 'Partial<RebarSet>' } },
    { type: 'rebarSet.delete', description: 'Delete a set and its bars (or keep the bars as manual).', fields: { id: 'string', keepBars: 'boolean?' } },
    { type: 'rebar.add', description: 'Add a single bar at a point.', fields: { rebar: '{ id?, name, centre:[x,y], diameter, materialId, strengthClassId?, probe? }' } },
    { type: 'rebar.update', description: 'Patch a bar (moving a generated bar detaches it from its set).', fields: { id: 'string', patch: 'Partial<Rebar>' } },
    { type: 'rebar.detach', description: 'Detach bars from their set.', fields: { ids: 'string[]' } },
    { type: 'rebar.delete', description: 'Delete bars.', fields: { ids: 'string[]' } },
    { type: 'series.add', description: 'Add a time series from points.', fields: { series: '{ id?, name, points:[[t s, value]...], interpolation:"linear"|"step", afterEnd:"hold"|"repeat"|"ambient", unit:"°C"|"W/m²", source:{kind:"manual"|"csv"|...} }' } },
    { type: 'series.addFromLibrary', description: 'Add a fire or climate curve from the library (iso834, external-fire, hydrocarbon, parametric-fire, rws, rabt-ztv-rail, rabt-ztv-road, hcm, astm-e119, ...). Idempotent by id.', fields: { libraryId: 'string', id: 'string?', name: 'string?', params: 'Record<string, number|string>?', duration: 's?' } },
    { type: 'series.generate', description: 'Generate a series: constant {value}, step {t0, before, after}, ramp {t0, t1, from, to}, sinusoid {mean, amplitude, period s, phase s?, duration s}, repeat {points, times}.', fields: { generator: 'string', params: 'Record<string, number|string>', name: 'string', id: 'string?', unit: '"°C"|"W/m²"?' } },
    { type: 'series.update', description: 'Patch a series.', fields: { id: 'string', patch: 'Partial<TimeSeries>' } },
    { type: 'series.delete', description: 'Delete an unused series.', fields: { id: 'string' } },
    { type: 'bc.add', description: 'Add a boundary condition and assign edges (each edge carries exactly one; assigning takes it from others).', fields: { bc: `{ id?, name, edgeRefs: ${EDGE}[], type:"fixed" (temperatureSeriesId) | "convection" (airSeriesId, alpha W/m²K or surfaceResistance m²K/W) | "convection-radiation" (gasSeriesId, radiationSeriesId?, alphaC=25, phi=1, epsM? (default: material emissivity), epsF=1) | "flux" (fluxSeriesId) | "insulated" }` } },
    { type: 'bc.update', description: 'Patch a boundary condition.', fields: { id: 'string', patch: 'object' } },
    { type: 'bc.assignEdges', description: 'Set / add / remove edges of a boundary condition.', fields: { id: 'string', edgeRefs: `${EDGE}[]`, mode: '"set"|"add"|"remove"' } },
    { type: 'bc.delete', description: 'Delete a boundary condition (edges become insulated).', fields: { id: 'string' } },
    { type: 'exposure.apply', description: 'Guided exposure: set conditions on whole faces in plain words. kinds: fire (ISO 834 by default, αc 25, εm from material, εf 1), fire-unexposed/ambient (αc 4 to ambient), insulated, indoor (Rsi 0.13/0.10/0.17), outdoor (Rse 0.04). Sides are found from the outward normal.', fields: { regionIds: 'string[]? (default all)', faces: '{ side:"bottom"|"top"|"left"|"right"|"all"|"exterior", kind:"fire"|"fire-unexposed"|"ambient"|"insulated"|"indoor"|"outdoor", seriesId?, params?:{alphaC,phi,epsM,epsF,alpha,surfaceResistance} }[]', fireCurve: 'library id? (default iso834)', fireDuration: 's?' } },
    { type: 'heatSource.add', description: 'Volumetric heat source in a region (W/m³, constant or series).', fields: { source: '{ id?, name, regionId, q?, seriesId? }' } },
    { type: 'heatSource.update', description: 'Patch a heat source.', fields: { id: 'string', patch: 'object' } },
    { type: 'heatSource.delete', description: 'Delete a heat source.', fields: { id: 'string' } },
    { type: 'probe.add', description: 'Add a probe at a point (section coordinates, mm).', fields: { probe: '{ id?, name?, position:[x,y], kind:"manual" }' } },
    { type: 'probe.addAtDepth', description: 'Add a probe at a depth below a face (on the inward normal).', fields: { edgeRef: EDGE, depth: 'mm', along: '0..1 (default 0.5)', name: 'string?' } },
    { type: 'probe.addForRebars', description: 'Switch automatic centre probes on for bars (on by default).', fields: { rebarIds: 'string[]?' } },
    { type: 'probe.update', description: 'Patch a probe.', fields: { id: 'string', patch: 'Partial<Probe>' } },
    { type: 'probe.delete', description: 'Delete probes.', fields: { ids: 'string[]' } },
    { type: 'lineProbe.add', description: 'Add a line along which a temperature profile is read.', fields: { lineProbe: '{ id?, name, from:[x,y], to:[x,y], samples? }' } },
    { type: 'lineProbe.update', description: 'Patch a line probe.', fields: { id: 'string', patch: 'object' } },
    { type: 'lineProbe.delete', description: 'Delete line probes.', fields: { ids: 'string[]' } },
    { type: 'analysis.add', description: 'Add an analysis.', fields: { analysis: '{ id?, name, mode:"steady"|"transient"|"periodic", duration s, dt s, initialTemperature °C, outputInterval s, tolerance:{residual,deltaTheta}, maxNewtonIterations, timeIntegration:"backward-euler"|"crank-nicolson", capacity:"lumped"|"consistent", adaptive:{enabled,maxDeltaPerStep,minDt}, periodic?:{maxCycles,tolerance} }' } },
    { type: 'analysis.update', description: 'Patch an analysis (e.g. duration 5400, dt 5).', fields: { id: 'string', patch: 'Partial<Analysis>' } },
    { type: 'analysis.delete', description: 'Delete an analysis.', fields: { id: 'string' } },
    { type: 'scenario.add', description: 'Add a variant of the model as overrides (shallow patches on entities).', fields: { scenario: '{ id?, name, overrides: { collection:"regions"|"materials"|"boundaryConditions"|"timeSeries"|"rebarSets"|"heatSources"|"analyses"|"settings"|"mesh", id?, patch }[] }' } },
    { type: 'scenario.update', description: 'Patch a scenario.', fields: { id: 'string', patch: 'Partial<Scenario>' } },
    { type: 'scenario.delete', description: 'Delete a scenario.', fields: { id: 'string' } },
    { type: 'metric.add', description: 'Add a named derived quantity.', fields: { metric: '{ id?, name, kind:"heat-flow"|"u-value"|"psi-value"|"min-surface-temperature"|"mean-surface-temperature"|"f-rsi"|"time-to-threshold"|"max-temperature"|"probe-temperature", edgeRefs?, probeId?, threshold?, time?, params? }' } },
    { type: 'metric.update', description: 'Patch a metric.', fields: { id: 'string', patch: 'Partial<Metric>' } },
    { type: 'metric.delete', description: 'Delete a metric.', fields: { id: 'string' } },
    { type: 'import.geometryWorkspace', description: 'Import regions from a geometry_workspace export (its `resolved` field).', fields: { json: 'object', materialId: 'string?' } },
    { type: 'import.polygonCsv', description: 'Import one polygon from "x;y" lines.', fields: { text: 'string', name: 'string?', materialId: 'string?' } },
    { type: 'import.dxf', description: 'Import closed polylines from a DXF text.', fields: { text: 'string', materialId: 'string?' } },
  ];
}
